این فایل کد حاوی پیاده سازی هم باdistilgpt2 و gpt2

# Decoder with English dataset

# **distilgpt2 Model**

In [1]:
!pip install transformers datasets torch seqeval scikit-learn

Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.47.1)
Collecting datasets
  Downloading datasets-3.2.0-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (2.5.1+cu121)
Collecting seqeval
  Downloading seqeval-1.2.2.tar.gz (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 2.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.16.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.24.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.27.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.21.0)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.4.5)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (17.0.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets) (2.2.2)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py310-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2024.9.0,>=2023.1.0 (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets)
  Downloading fsspec-2024.9.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets) (3.11.10)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch) (3.1.4)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2024.12.14)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-3.2.0-py3-none-any.whl (480 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 15.1 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 11.9 MB/s eta 0:00:00
Downloading fsspec-2024.9.0-py3-none-any.whl (179 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 13.5 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py310-none-any.whl (134 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 10.6 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 12.3 MB/s eta 0:00:00
Building wheels for collected packages: seqeval
  Building wheel for seqeval (setup.py) ... done
  Created wheel for seqeval: filename=seqeval-1.2.2-py3-none-any.whl size=16161 sha256=d9ffa231584cde92f378bba7199e0fcb9a01ec939ca617d8f57734e5fa9bf8c8
  Stored in directory: /root/.cache/pip/wheels/1a/67/4a/ad4082dd7dfc30f2abfe4d80a2ed5926a506eb8a972b4767fa
Successfully built seqeval
Installing collected packages: xxhash, fsspec, dill, multiprocess, seqeval, datasets
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2024.10.0
    Uninstalling fsspec-2024.10.0:
      Successfully uninstalled fsspec-2024.10.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.9.0 which is incompatible.
Successfully installed datasets-3.2.0 dill-0.3.8 fsspec-2024.9.0 multiprocess-0.70.16 seqeval-1.2.2 xxhash-3.5.0

In [2]:
import json
import torch
import numpy as np
from transformers import GPT2TokenizerFast, GPT2LMHeadModel, Trainer, TrainingArguments
from datasets import Dataset, DatasetDict
from seqeval.metrics import f1_score as seq_f1, precision_score as seq_precision, recall_score as seq_recall, classification_report
from sklearn.metrics import f1_score as sklearn_f1, precision_score as sklearn_precision, recall_score as sklearn_recall
import random
from sklearn.model_selection import train_test_split
from collections import Counter

In [4]:
tokenizer = GPT2TokenizerFast.from_pretrained('distilgpt2')
tokenizer.add_special_tokens({'pad_token': '[PAD]'})
model = GPT2LMHeadModel.from_pretrained('distilgpt2')
model.resize_token_embeddings(len(tokenizer))
model.config.pad_token_id = tokenizer.pad_token_id
model.config.use_cache = False

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/762 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/353M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

The new embeddings will be initialized from a multivariate normal distribution that has old embeddings' mean and covariance. As described in this article: https://nlp.stanford.edu/~johnhew/vocab-expansion.html. To disable this, use `mean_resizing=False`

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50258, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-5): 6 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2SdpaAttention(
          (c_attn): Conv1D(nf=2304, nx=768)
          (c_proj): Conv1D(nf=768, nx=768)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D(nf=3072, nx=768)
          (c_proj): Conv1D(nf=768, nx=3072)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50258, bias=False)
)

## BIOایجاد توکن‌ها و برچسب‌ها با استفاده از برچسب گذاری

In [10]:
def create_tokens_and_labels(id, sample):
    intent = sample['intent']
    utt = sample['utt']
    annot_utt = sample['annot_utt']
    tokens = utt.split()
    labels = []
    label = 'O'
    split_annot_utt = annot_utt.split()
    idx = 0
    BIO_SLOT = False
    while idx < len(split_annot_utt):
        if split_annot_utt[idx].startswith('['):
            label = split_annot_utt[idx].lstrip('[')
            idx += 2
            BIO_SLOT = True
        elif split_annot_utt[idx].endswith(']'):
            if split_annot_utt[idx-1] == ":":
                labels.append("B-" + label)
                label = 'O'
                idx += 1
            else:
                labels.append("I-" + label)
                label = 'O'
                idx += 1
            BIO_SLOT = False
        else:
            if split_annot_utt[idx-1] == ":":
                labels.append("B-" + label)
                idx += 1
            elif BIO_SLOT:
                labels.append("I-" + label)
                idx += 1
            else:
                labels.append("O")
                idx += 1

    if len(tokens) != len(labels):
        raise ValueError(f"Length of tokens, {tokens}, doesn't match length of labels, {labels}, "
                         f"for id {id} and annot_utt: {annot_utt}")
    return tokens, labels, intent

sentences_tr, tags_tr, intent_tags_tr = [], [], []
sentences_val, tags_val, intent_tags_val = [], [], []
sentences_test, tags_test, intent_tags_test = [], [], []

massive_raw = []
with open('/content/drive/MyDrive/en-US.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        massive_raw.append(json.loads(line))

for id, sample in enumerate(massive_raw):
    tokens, labels, intent = create_tokens_and_labels(id, sample)
    if sample['partition'] == 'train':
        sentences_tr.append(tokens)
        tags_tr.append(labels)
        intent_tags_tr.append(intent)
    elif sample['partition'] == 'dev':
        sentences_val.append(tokens)
        tags_val.append(labels)
        intent_tags_val.append(intent)
    elif sample['partition'] == 'test':
        sentences_test.append(tokens)
        tags_test.append(labels)
        intent_tags_test.append(intent)


sentences_tr, _, tags_tr, _, intent_tags_tr, _ = train_test_split(
    sentences_tr, tags_tr, intent_tags_tr, test_size=0.9, random_state=42)

val_indices = random.sample(range(len(sentences_val)), 200)
sentences_val = [sentences_val[i] for i in val_indices]
tags_val = [tags_val[i] for i in val_indices]
intent_tags_val = [intent_tags_val[i] for i in val_indices]


test_indices = random.sample(range(len(sentences_test)), 200)
sentences_test = [sentences_test[i] for i in test_indices]
tags_test = [tags_test[i] for i in test_indices]
intent_tags_test = [intent_tags_test[i] for i in test_indices]

partition_counts = {'train': len(sentences_tr), 'test': len(sentences_test), 'dev': len(sentences_val)}
print("تعداد نمونه‌ها در هر بخش:", partition_counts)

تعداد نمونه‌ها در هر بخش: {'train': 1151, 'test': 200, 'dev': 200}

**استخراج لیست برچسب‌ها قصد و شکاف**

In [11]:
unique_slot_labels = set(label for sublist in tags_tr + tags_val + tags_test for label in sublist)
unique_intent_labels = set(intent_tags_tr + intent_tags_val + intent_tags_test)

label_list = sorted(unique_slot_labels.union(unique_intent_labels))

print("\nلیست برچسب‌های استخراج شده به صورت خودکار:")
print(label_list)

لیست برچسب‌های استخراج شده به صورت خودکار:
['B-alarm_type', 'B-app_name', 'B-artist_name', 'B-audiobook_author', 'B-audiobook_name', 'B-business_name', 'B-business_type', 'B-change_amount', 'B-color_type', 'B-cooking_type', 'B-currency_name', 'B-date', 'B-definition_word', 'B-device_type', 'B-drink_type', 'B-email_address', 'B-email_folder', 'B-event_name', 'B-food_type', 'B-game_name', 'B-general_frequency', 'B-house_place', 'B-ingredient', 'B-joke_type', 'B-list_name', 'B-meal_type', 'B-media_type', 'B-movie_name', 'B-movie_type', 'B-music_descriptor', 'B-music_genre', 'B-news_topic', 'B-order_type', 'B-person', 'B-personal_info', 'B-place_name', 'B-player_setting', 'B-playlist_name', 'B-podcast_descriptor', 'B-podcast_name', 'B-radio_name', 'B-relation', 'B-song_name', 'B-time', 'B-time_zone', 'B-timeofday', 'B-transport_agency', 'B-transport_descriptor', 'B-transport_type', 'B-weather_descriptor', 'I-alarm_type', 'I-artist_name', 'I-audiobook_author', 'I-audiobook_name', 'I-business_name', 'I-business_type', 'I-change_amount', 'I-color_type', 'I-currency_name', 'I-date', 'I-definition_word', 'I-device_type', 'I-drink_type', 'I-email_address', 'I-event_name', 'I-food_type', 'I-game_name', 'I-general_frequency', 'I-house_place', 'I-list_name', 'I-media_type', 'I-movie_name', 'I-movie_type', 'I-music_descriptor', 'I-music_genre', 'I-news_topic', 'I-order_type', 'I-person', 'I-personal_info', 'I-place_name', 'I-player_setting', 'I-playlist_name', 'I-podcast_descriptor', 'I-podcast_name', 'I-radio_name', 'I-relation', 'I-song_name', 'I-time', 'I-time_zone', 'I-timeofday', 'I-weather_descriptor', 'O', 'alarm_query', 'alarm_remove', 'alarm_set', 'audio_volume_down', 'audio_volume_mute', 'audio_volume_other', 'audio_volume_up', 'calendar_query', 'calendar_remove', 'calendar_set', 'cooking_recipe', 'datetime_convert', 'datetime_query', 'email_addcontact', 'email_query', 'email_querycontact', 'email_sendemail', 'general_greet', 'general_joke', 'general_quirky', 'iot_cleaning', 'iot_coffee', 'iot_hue_lightchange', 'iot_hue_lightdim', 'iot_hue_lightoff', 'iot_hue_lighton', 'iot_hue_lightup', 'iot_wemo_off', 'iot_wemo_on', 'lists_createoradd', 'lists_query', 'lists_remove', 'music_dislikeness', 'music_likeness', 'music_query', 'music_settings', 'news_query', 'play_audiobook', 'play_game', 'play_music', 'play_podcasts', 'play_radio', 'qa_currency', 'qa_definition', 'qa_factoid', 'qa_maths', 'qa_stock', 'recommendation_events', 'recommendation_locations', 'recommendation_movies', 'social_post', 'social_query', 'takeaway_order', 'takeaway_query', 'transport_query', 'transport_taxi', 'transport_ticket', 'transport_traffic', 'weather_query']

**تابع برای ایجاد پرامپ**

In [12]:
def create_prompt(sentence, intent, slots):

    sentence_text = ' '.join(sentence)
    slots_text = ' '.join(slots)
    prompt = f'Input: {sentence_text}\nOutput Intent: {intent}\nOutput Slots: {slots_text}'
    return prompt

train_prompts = [create_prompt(sent, intent, slots) for sent, intent, slots in zip(sentences_tr, intent_tags_tr, tags_tr)]

val_prompts = [create_prompt(sent, intent, slots) for sent, intent, slots in zip(sentences_val, intent_tags_val, tags_val)]

test_prompts = [create_prompt(sent, intent, slots) for sent, intent, slots in zip(sentences_test, intent_tags_test, tags_test)]

print("نمونه‌های پرامپت‌های آموزشی:")
for i in range(2):
    print(f"Training Prompt {i+1}:")
    print(train_prompts[i])
    print("\n")

print("نمونه‌های پرامپت‌های اعتبارسنجی:")
for i in range(2):
    print(f"Validation Prompt {i+1}:")
    print(val_prompts[i])
    print("\n")

print("نمونه‌های پرامپت‌های تست:")
for i in range(2):
    print(f"Test Prompt {i+1}:")
    print(test_prompts[i])
    print("\n")

نمونه‌های پرامپت‌های آموزشی:
Training Prompt 1:
Input: please remove dinner date scheduled for this friday at nine p. m.
Output Intent: calendar_remove
Output Slots: O O B-meal_type O O O O B-date O B-time I-time I-time


Training Prompt 2:
Input: read freds emails
Output Intent: email_query
Output Slots: O B-person O


نمونه‌های پرامپت‌های اعتبارسنجی:
Validation Prompt 1:
Input: make a new list
Output Intent: lists_createoradd
Output Slots: O O O O


Validation Prompt 2:
Input: power off the current
Output Intent: iot_hue_lightoff
Output Slots: O O O O


نمونه‌های پرامپت‌های تست:
Test Prompt 1:
Input: please be quiet for another hour
Output Intent: audio_volume_mute
Output Slots: O O O O B-time I-time


Test Prompt 2:
Input: where is yosemite park
Output Intent: qa_factoid
Output Slots: O O B-place_name I-place_name

# distilgpt2پیش پردازش وتوکنایز داده‌ها با مدل پیش‌آموزش دیده

In [13]:
def tokenize_function(examples):

    tokenized = tokenizer(
        examples['text'],
        padding='max_length',
        truncation=True,
        max_length=70,
        return_offsets_mapping=True
    )

    labels = []
    for i, slot_labels in enumerate(examples['slot_labels']):
        label_ids = [-100] * len(tokenized['input_ids'][i])


        output_slots_prefix = 'Output Slots: '
        output_slots_prefix_ids = tokenizer.encode(output_slots_prefix, add_special_tokens=False)

        try:

            prefix_start = tokenized['input_ids'][i].index(output_slots_prefix_ids[0])
            for j in range(len(output_slots_prefix_ids)):
                label_ids[prefix_start + j] = -100
            slot_start = prefix_start + len(output_slots_prefix_ids)


            for k, slot in enumerate(slot_labels):
                if slot in label_list:
                    label_id = label_list.index(slot)
                    if slot_start + k < len(label_ids):
                        label_ids[slot_start + k] = label_id
                else:
                    label_ids[slot_start + k] = -100
        except ValueError:

            pass

        labels.append(label_ids)

    tokenized['labels'] = labels
    return tokenized

# تبدیل پرامپت‌ها به دیکشنری همراه با برچسب‌ها
train_data = {'text': train_prompts, 'slot_labels': tags_tr}
val_data = {'text': val_prompts, 'slot_labels': tags_val}
test_data = {'text': test_prompts, 'slot_labels': tags_test}

train_dataset = Dataset.from_dict(train_data)
val_dataset = Dataset.from_dict(val_data)
test_dataset = Dataset.from_dict(test_data)


dataset = DatasetDict({
    'train': train_dataset,
    'validation': val_dataset,
    'test': test_dataset
})

tokenized_datasets = dataset.map(tokenize_function, batched=True)

Map:   0%|          | 0/1151 [00:00<?, ? examples/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

# تعریف تابع برای محاسبه متریک‌ها در آموزش

In [14]:
def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    preds = np.argmax(predictions, axis=-1)


    preds = preds.tolist()
    labels = labels.tolist()

    true_labels = []
    true_preds = []

    for pred, label in zip(preds, labels):
        temp_true_labels = []
        temp_true_preds = []
        for p, l in zip(pred, label):
            if l != -100:
                temp_true_labels.append(l)
                temp_true_preds.append(p)
        true_labels.append(temp_true_labels)
        true_preds.append(temp_true_preds)

    true_labels_text = [[label_list[l] for l in labels] for labels in true_labels]
    preds_text = [[label_list[p] for p in preds] for preds in true_preds]

    slot_f1_micro = seq_f1(true_labels_text, preds_text, average='micro')
    slot_precision_micro = seq_precision(true_labels_text, preds_text, average='micro')
    slot_recall_micro = seq_recall(true_labels_text, preds_text, average='micro')


    true_intents = [labels[-1] for labels in true_labels if len(labels) > 0]
    pred_intents = [preds[-1] for preds in true_preds if len(preds) > 0]

    true_intents_text = [label_list[l] for l in true_intents]
    pred_intents_text = [label_list[p] for p in pred_intents]

    intent_f1_micro = sklearn_f1(true_intents_text, pred_intents_text, average='micro')
    intent_precision_micro = sklearn_precision(true_intents_text, pred_intents_text, average='micro')
    intent_recall_micro = sklearn_recall(true_intents_text, pred_intents_text, average='micro')

    return {
        'slot_f1_micro': slot_f1_micro,
        'slot_precision_micro': slot_precision_micro,
        'slot_recall_micro': slot_recall_micro,
        'intent_f1_micro': intent_f1_micro,
        'intent_precision_micro': intent_precision_micro,
        'intent_recall_micro': intent_recall_micro,
    }

# آموزش

In [15]:
training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=5,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=4,
    learning_rate=5e-5,
    logging_dir='./logs',
    logging_steps=50,
    save_total_limit=2,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    fp16=True,
    gradient_checkpointing=True,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    report_to=[],
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['validation'],
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
)


trainer.train()
torch.cuda.empty_cache()

trainer.save_model('./trained_gpt2_model')
torch.cuda.empty_cache()

/usr/local/lib/python3.10/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
<ipython-input-15-07e5b957a675>:22: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

# ارزیابی مدل

In [16]:
def get_labels(predictions, label_ids):

    preds = np.argmax(predictions, axis=-1)
    labels = label_ids

    preds = preds.tolist()
    labels = labels.tolist()

    true_labels = []
    true_preds = []

    for pred, label in zip(preds, labels):
        temp_true_labels = []
        temp_true_preds = []
        for p, l in zip(pred, label):
            if l != -100:
                temp_true_labels.append(l)
                temp_true_preds.append(p)
        true_labels.append(temp_true_labels)
        true_preds.append(temp_true_preds)

    return true_labels, true_preds

def id_to_label(id_list, label_map):

    return [[label_map[id] for id in labels] for labels in id_list]

def predict_in_batches(trainer, dataset, batch_size=16):
    predictions = []
    label_ids = []
    for i in range(0, len(dataset), batch_size):
        batch = dataset.select(range(i, min(i + batch_size, len(dataset))))
        results = trainer.predict(batch)
        predictions.append(results.predictions)
        label_ids.append(results.label_ids)
        torch.cuda.empty_cache()
    predictions = np.concatenate(predictions, axis=0)
    label_ids = np.concatenate(label_ids, axis=0)
    return predictions, label_ids

val_predictions, val_label_ids = predict_in_batches(trainer, tokenized_datasets['validation'], batch_size=16)

val_true_labels, val_preds = get_labels(val_predictions, val_label_ids)

val_true_labels_text = id_to_label(val_true_labels, label_list)
val_preds_text = id_to_label(val_preds, label_list)

val_f1_micro = seq_f1(val_true_labels_text, val_preds_text, average='micro')
val_precision_micro = seq_precision(val_true_labels_text, val_preds_text, average='micro')
val_recall_micro = seq_recall(val_true_labels_text, val_preds_text, average='micro')

print("\nValidation Slot Filling Metrics (Micro):")
print(f"Precision: {val_precision_micro:.4f}")
print(f"Recall: {val_recall_micro:.4f}")
print(f"F1 Score: {val_f1_micro:.4f}")

val_f1_macro = seq_f1(val_true_labels_text, val_preds_text, average='macro')
val_precision_macro = seq_precision(val_true_labels_text, val_preds_text, average='macro')
val_recall_macro = seq_recall(val_true_labels_text, val_preds_text, average='macro')

print("\nValidation Slot Filling Metrics (Macro):")
print(f"Precision: {val_precision_macro:.4f}")
print(f"Recall: {val_recall_macro:.4f}")
print(f"F1 Score: {val_f1_macro:.4f}")

print("\nValidation Slot Filling Classification Report:")
print(classification_report(val_true_labels_text, val_preds_text, digits=4))


val_true_intents = [labels[-1] for labels in val_true_labels if len(labels) > 0]
val_pred_intents = [preds[-1] for preds in val_preds if len(preds) > 0]


val_true_intents_text = [label_list[id] for id in val_true_intents]
val_pred_intents_text = [label_list[id] for id in val_pred_intents]

intent_f1_micro = sklearn_f1(val_true_intents_text, val_pred_intents_text, average='micro')
intent_precision_micro = sklearn_precision(val_true_intents_text, val_pred_intents_text, average='micro')
intent_recall_micro = sklearn_recall(val_true_intents_text, val_pred_intents_text, average='micro')

print("\nValidation Intent Detection Metrics (Micro):")
print(f"Precision: {intent_precision_micro:.4f}")
print(f"Recall: {intent_recall_micro:.4f}")
print(f"F1 Score: {intent_f1_micro:.4f}")

intent_f1_macro = sklearn_f1(val_true_intents_text, val_pred_intents_text, average='macro')
intent_precision_macro = sklearn_precision(val_true_intents_text, val_pred_intents_text, average='macro')
intent_recall_macro = sklearn_recall(val_true_intents_text, val_pred_intents_text, average='macro')

print("\nValidation Intent Detection Metrics (Macro):")
print(f"Precision: {intent_precision_macro:.4f}")
print(f"Recall: {intent_recall_macro:.4f}")
print(f"F1 Score: {intent_f1_macro:.4f}")

print("\nValidation Intent Detection Classification Report (sklearn):")
print(sklearn_classification_report(val_true_intents_text, val_pred_intents_text, digits=4))


torch.cuda.empty_cache()

test_predictions, test_label_ids = predict_in_batches(trainer, tokenized_datasets['test'], batch_size=16)

test_true_labels, test_preds = get_labels(test_predictions, test_label_ids)


test_true_labels_text = id_to_label(test_true_labels, label_list)
test_preds_text = id_to_label(test_preds, label_list)


test_f1_micro = seq_f1(test_true_labels_text, test_preds_text, average='micro')
test_precision_micro = seq_precision(test_true_labels_text, test_preds_text, average='micro')
test_recall_micro = seq_recall(test_true_labels_text, test_preds_text, average='micro')

print("\nTest Slot Filling Metrics (Micro):")
print(f"Precision: {test_precision_micro:.4f}")
print(f"Recall: {test_recall_micro:.4f}")
print(f"F1 Score: {test_f1_micro:.4f}")


test_f1_macro = seq_f1(test_true_labels_text, test_preds_text, average='macro')
test_precision_macro = seq_precision(test_true_labels_text, test_preds_text, average='macro')
test_recall_macro = seq_recall(test_true_labels_text, test_preds_text, average='macro')

print("\nTest Slot Filling Metrics (Macro):")
print(f"Precision: {test_precision_macro:.4f}")
print(f"Recall: {test_recall_macro:.4f}")
print(f"F1 Score: {test_f1_macro:.4f}")


print("\nTest Slot Filling Classification Report:")
print(classification_report(test_true_labels_text, test_preds_text, digits=4))


test_true_intents = [labels[-1] for labels in test_true_labels if len(labels) > 0]
test_pred_intents = [preds[-1] for preds in test_preds if len(preds) > 0]

test_true_intents_text = [label_list[id] for id in test_true_intents]
test_pred_intents_text = [label_list[id] for id in test_pred_intents]

test_intent_f1_micro = sklearn_f1(test_true_intents_text, test_pred_intents_text, average='micro')
test_intent_precision_micro = sklearn_precision(test_true_intents_text, test_pred_intents_text, average='micro')
test_intent_recall_micro = sklearn_recall(test_true_intents_text, test_pred_intents_text, average='micro')

print("\nTest Intent Detection Metrics (Micro):")
print(f"Precision: {test_intent_precision_micro:.4f}")
print(f"Recall: {test_intent_recall_micro:.4f}")
print(f"F1 Score: {test_intent_f1_micro:.4f}")

test_intent_f1_macro = sklearn_f1(test_true_intents_text, test_pred_intents_text, average='macro')
test_intent_precision_macro = sklearn_precision(test_true_intents_text, test_pred_intents_text, average='macro')
test_intent_recall_macro = sklearn_recall(test_true_intents_text, test_pred_intents_text, average='macro')

print("\nTest Intent Detection Metrics (Macro):")
print(f"Precision: {test_intent_precision_macro:.4f}")
print(f"Recall: {test_intent_recall_macro:.4f}")
print(f"F1 Score: {test_intent_f1_macro:.4f}")

print("\nTest Intent Detection Classification Report (sklearn):")
print(sklearn_classification_report(test_true_intents_text, test_pred_intents_text, digits=4))

decoded_text = tokenizer.decode(tokenized_datasets['train'][0]['input_ids'], skip_special_tokens=True)
print("\nمتن بازگردانی‌شده:")
print(decoded_text)
original_text = tokenized_datasets['train'][0]['text']
print("\nمتن اصلی:")
print(original_text)

Validation Slot Filling Metrics (Micro):
Precision: 0.1538
Recall: 0.1478
F1 Score: 0.1508

Validation Slot Filling Metrics (Macro):
Precision: 0.1202
Recall: 0.1397
F1 Score: 0.1098

Validation Slot Filling Classification Report:
                    precision    recall  f1-score   support

       artist_name     0.0000    0.0000    0.0000         5
    audiobook_name     0.1429    0.2500    0.1818         4
     business_name     0.1000    0.1429    0.1176         7
     business_type     0.2500    1.0000    0.4000         1
        color_type     1.0000    0.5000    0.6667         2
     currency_name     0.0000    0.0000    0.0000         5
              date     0.1594    0.3333    0.2157        33
   definition_word     0.4286    1.0000    0.6000         3
       device_type     0.0000    0.0000    0.0000         3
        drink_type     0.0000    0.0000    0.0000         1
      email_folder     0.0000    0.0000    0.0000         1
        event_name     0.0000    0.0000    0.0000         9
         food_type     0.0000    0.0000    0.0000         5
         game_name     0.0000    0.0000    0.0000         2
 general_frequency     0.0000    0.0000    0.0000         1
       house_place     0.0000    0.0000    0.0000         3
         joke_type     0.0000    0.0000    0.0000         1
         list_name     0.3333    0.2500    0.2857         4
         meal_type     0.0000    0.0000    0.0000         2
        media_type     0.5000    0.0667    0.1176        15
  music_descriptor     0.0000    0.0000    0.0000         1
        order_type     0.2500    0.5000    0.3333         2
            person     0.0909    0.0714    0.0800        14
     personal_info     0.0000    0.0000    0.0000         2
        place_name     0.1176    0.1481    0.1311        27
    player_setting     0.0000    0.0000    0.0000         7
     playlist_name     0.0000    0.0000    0.0000         0
      podcast_name     0.0000    0.0000    0.0000         2
        radio_name     0.5000    0.3333    0.4000         3
          relation     0.0000    0.0000    0.0000         2
         song_name     0.0000    0.0000    0.0000         2
              time     0.0833    0.0714    0.0769        14
         timeofday     0.2500    0.2222    0.2353         9
    transport_type     0.0000    0.0000    0.0000         5
weather_descriptor     0.0000    0.0000    0.0000         6

         micro avg     0.1538    0.1478    0.1508       203
         macro avg     0.1202    0.1397    0.1098       203
      weighted avg     0.1417    0.1478    0.1223       203


Validation Intent Detection Metrics (Micro):
Precision: 0.5650
Recall: 0.5650
F1 Score: 0.5650

Validation Intent Detection Metrics (Macro):
Precision: 0.2071
Recall: 0.2385
F1 Score: 0.1957

Validation Intent Detection Classification Report (sklearn):
                    precision    recall  f1-score   support

     B-artist_name     0.0000    0.0000    0.0000         4
  B-audiobook_name     0.0000    0.0000    0.0000         1
   B-business_name     0.3333    1.0000    0.5000         1
      B-color_type     1.0000    0.5000    0.6667         2
   B-currency_name     0.0000    0.0000    0.0000         2
            B-date     0.3000    0.6667    0.4138         9
 B-definition_word     0.3333    1.0000    0.5000         1
    B-email_folder     0.0000    0.0000    0.0000         1
      B-event_name     0.0000    0.0000    0.0000         1
       B-food_type     0.0000    0.0000    0.0000         2
       B-list_name     0.0000    0.0000    0.0000         0
      B-media_type     1.0000    0.3333    0.5000         3
      B-order_type     0.5000    1.0000    0.6667         1
          B-person     0.2500    0.5000    0.3333         2
      B-place_name     0.3077    0.3077    0.3077        13
        B-relation     0.0000    0.0000    0.0000         2
       B-song_name     0.0000    0.0000    0.0000         1
            B-time     0.0000    0.0000    0.0000         1
       B-timeofday     1.0000    0.2857    0.4444         7
  B-transport_type     0.0000    0.0000    0.0000         0
     I-artist_name     0.0000    0.0000    0.0000         1
  I-audiobook_name     0.5000    0.6667    0.5714         3
   I-business_name     0.0000    0.0000    0.0000         0
            I-date     0.2000    0.1429    0.1667         7
     I-device_type     0.5000    0.5000    0.5000         2
      I-drink_type     0.0000    0.0000    0.0000         1
      I-event_name     0.0000    0.0000    0.0000         1
       I-food_type     0.0000    0.0000    0.0000         0
       I-game_name     0.5000    1.0000    0.6667         1
     I-house_place     0.0000    0.0000    0.0000         1
      I-media_type     0.0000    0.0000    0.0000         4
I-music_descriptor     0.0000    0.0000    0.0000         1
          I-person     0.0000    0.0000    0.0000         5
   I-personal_info     0.0000    0.0000    0.0000         1
      I-place_name     0.0000    0.0000    0.0000         6
   I-playlist_name     0.0000    0.0000    0.0000         0
    I-podcast_name     0.0000    0.0000    0.0000         1
      I-radio_name     0.5000    0.5000    0.5000         2
            I-time     0.3333    0.2857    0.3077         7
                 O     0.7250    0.8529    0.7838       102

          accuracy                         0.5650       200
         macro avg     0.2071    0.2385    0.1957       200
      weighted avg     0.5103    0.5650    0.5182       200

/usr/local/lib/python3.10/dist-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Test Slot Filling Metrics (Micro):
Precision: 0.1596
Recall: 0.1676
F1 Score: 0.1635

Test Slot Filling Metrics (Macro):
Precision: 0.0881
Recall: 0.0922
F1 Score: 0.0791

Test Slot Filling Classification Report:
                    precision    recall  f1-score   support

       artist_name     0.0000    0.0000    0.0000         8
     business_name     0.0000    0.0000    0.0000         4
     business_type     0.0000    0.0000    0.0000         3
      cooking_type     0.0000    0.0000    0.0000         1
     currency_name     0.0000    0.0000    0.0000         1
              date     0.2292    0.4583    0.3056        24
   definition_word     0.4286    0.7500    0.5455         4
       device_type     0.0000    0.0000    0.0000         4
      email_folder     0.0000    0.0000    0.0000         1
        event_name     0.2500    0.2381    0.2439        21
         food_type     0.0000    0.0000    0.0000         5
         game_name     0.0000    0.0000    0.0000         1
       house_place     0.0000    0.0000    0.0000         4
         joke_type     0.0000    0.0000    0.0000         3
         list_name     1.0000    0.2500    0.4000         4
        media_type     0.0000    0.0000    0.0000         6
  music_descriptor     0.0000    0.0000    0.0000         1
       music_genre     0.0000    0.0000    0.0000         9
        news_topic     0.0000    0.0000    0.0000         1
            person     0.1111    0.1250    0.1176        16
        place_name     0.2500    0.3125    0.2778        16
    player_setting     0.0000    0.0000    0.0000         2
     playlist_name     0.0000    0.0000    0.0000         1
podcast_descriptor     0.0000    0.0000    0.0000         1
        radio_name     0.0000    0.0000    0.0000         2
          relation     0.0000    0.0000    0.0000         4
         song_name     0.0000    0.0000    0.0000         2
              time     0.0625    0.0588    0.0606        17
         timeofday     0.4000    0.6667    0.5000         3
    transport_type     0.0000    0.0000    0.0000         5
weather_descriptor     0.0000    0.0000    0.0000         5

         micro avg     0.1596    0.1676    0.1635       179
         macro avg     0.0881    0.0922    0.0791       179
      weighted avg     0.1369    0.1676    0.1402       179


Test Intent Detection Metrics (Micro):
Precision: 0.6350
Recall: 0.6350
F1 Score: 0.6350

Test Intent Detection Metrics (Macro):
Precision: 0.2199
Recall: 0.2377
F1 Score: 0.2074

Test Intent Detection Classification Report (sklearn):
                   precision    recall  f1-score   support

    B-artist_name     0.0000    0.0000    0.0000         0
  B-business_type     0.0000    0.0000    0.0000         0
           B-date     0.5833    0.7778    0.6667         9
B-definition_word     0.6000    1.0000    0.7500         3
    B-device_type     0.0000    0.0000    0.0000         1
     B-event_name     1.0000    0.5000    0.6667         2
      B-food_type     0.0000    0.0000    0.0000         3
      B-game_name     0.0000    0.0000    0.0000         0
    B-house_place     0.0000    0.0000    0.0000         1
      B-joke_type     0.0000    0.0000    0.0000         1
     B-media_type     0.0000    0.0000    0.0000         3
    B-music_genre     0.0000    0.0000    0.0000         1
         B-person     0.3333    0.5000    0.4000         4
     B-place_name     0.4444    1.0000    0.6154         4
     B-radio_name     0.0000    0.0000    0.0000         0
       B-relation     0.0000    0.0000    0.0000         3
           B-time     0.0000    0.0000    0.0000         2
      B-timeofday     1.0000    1.0000    1.0000         2
    I-artist_name     0.0000    0.0000    0.0000         3
  I-business_name     0.0000    0.0000    0.0000         1
  I-business_type     0.0000    0.0000    0.0000         1
           I-date     0.7500    0.5000    0.6000         6
I-definition_word     0.0000    0.0000    0.0000         1
    I-device_type     0.0000    0.0000    0.0000         3
     I-event_name     0.3333    0.5000    0.4000         2
      I-food_type     0.0000    0.0000    0.0000         0
      I-game_name     1.0000    1.0000    1.0000         1
    I-house_place     0.0000    0.0000    0.0000         2
     I-media_type     0.0000    0.0000    0.0000         1
    I-music_genre     0.0000    0.0000    0.0000         2
     I-news_topic     0.0000    0.0000    0.0000         0
         I-person     0.0000    0.0000    0.0000         1
     I-place_name     1.0000    0.1667    0.2857         6
  I-playlist_name     0.0000    0.0000    0.0000         1
     I-radio_name     0.2500    1.0000    0.4000         1
      I-song_name     0.0000    0.0000    0.0000         2
           I-time     0.5000    0.5000    0.5000        10
      I-timeofday     0.0000    0.0000    0.0000         1
                O     0.7805    0.8276    0.8033       116

         accuracy                         0.6350       200
        macro avg     0.2199    0.2377    0.2074       200
     weighted avg     0.6106    0.6350    0.6067       200


متن بازگردانی‌شده:
Input: please remove dinner date scheduled for this friday at nine p. m.
Output Intent: calendar_remove
Output Slots: O O B-meal_type O O O O B-date O B-time I-time I-time

متن اصلی:
Input: please remove dinner date scheduled for this friday at nine p. m.
Output Intent: calendar_remove
Output Slots: O O B-meal_type O O O O B-date O B-time I-time I-time

/usr/local/lib/python3.10/dist-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# **GPT2 Model**



---



---



---

In [1]:
!pip install transformers datasets torch seqeval scikit-learn

Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.47.1)
Collecting datasets
  Downloading datasets-3.2.0-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (2.5.1+cu121)
Collecting seqeval
  Downloading seqeval-1.2.2.tar.gz (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 2.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.16.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.24.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.27.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.21.0)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.4.5)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (17.0.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets) (2.2.2)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py310-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2024.9.0,>=2023.1.0 (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets)
  Downloading fsspec-2024.9.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets) (3.11.10)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch) (3.1.4)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2024.12.14)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-3.2.0-py3-none-any.whl (480 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 14.6 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 11.3 MB/s eta 0:00:00
Downloading fsspec-2024.9.0-py3-none-any.whl (179 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 14.5 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py310-none-any.whl (134 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 10.8 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 17.5 MB/s eta 0:00:00
Building wheels for collected packages: seqeval
  Building wheel for seqeval (setup.py) ... done
  Created wheel for seqeval: filename=seqeval-1.2.2-py3-none-any.whl size=16161 sha256=8e5911503c3b5bcd9bdb6d7be9358196bbb41d223c9c5ab2423adecdbbe4dea7
  Stored in directory: /root/.cache/pip/wheels/1a/67/4a/ad4082dd7dfc30f2abfe4d80a2ed5926a506eb8a972b4767fa
Successfully built seqeval
Installing collected packages: xxhash, fsspec, dill, multiprocess, seqeval, datasets
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2024.10.0
    Uninstalling fsspec-2024.10.0:
      Successfully uninstalled fsspec-2024.10.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.9.0 which is incompatible.
Successfully installed datasets-3.2.0 dill-0.3.8 fsspec-2024.9.0 multiprocess-0.70.16 seqeval-1.2.2 xxhash-3.5.0

In [2]:
import json
import torch
import numpy as np
from transformers import GPT2TokenizerFast, GPT2LMHeadModel, Trainer, TrainingArguments
from datasets import Dataset, DatasetDict
from seqeval.metrics import f1_score as seq_f1, precision_score as seq_precision, recall_score as seq_recall, classification_report
from sklearn.metrics import f1_score as sklearn_f1, precision_score as sklearn_precision, recall_score as sklearn_recall
import random
from sklearn.model_selection import train_test_split
from collections import Counter
from transformers import GPT2TokenizerFast, GPT2LMHeadModel, Trainer, TrainingArguments

# مدل GPT2

In [3]:
tokenizer = GPT2TokenizerFast.from_pretrained('gpt2')
tokenizer.add_special_tokens({'pad_token': '[PAD]'})
model = GPT2LMHeadModel.from_pretrained('gpt2')
model.resize_token_embeddings(len(tokenizer))
model.config.pad_token_id = tokenizer.pad_token_id
model.config.use_cache = False
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

The new embeddings will be initialized from a multivariate normal distribution that has old embeddings' mean and covariance. As described in this article: https://nlp.stanford.edu/~johnhew/vocab-expansion.html. To disable this, use `mean_resizing=False`

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50258, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2SdpaAttention(
          (c_attn): Conv1D(nf=2304, nx=768)
          (c_proj): Conv1D(nf=768, nx=768)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D(nf=3072, nx=768)
          (c_proj): Conv1D(nf=768, nx=3072)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50258, bias=False)
)

# **BIOایجاد توکن‌ها و برچسب‌ها با استفاده از برچسب گذاری**

In [4]:
def create_tokens_and_labels(id, sample):
    intent = sample['intent']
    utt = sample['utt']
    annot_utt = sample['annot_utt']
    tokens = utt.split()
    labels = []
    label = 'O'
    split_annot_utt = annot_utt.split()
    idx = 0
    BIO_SLOT = False
    while idx < len(split_annot_utt):
        if split_annot_utt[idx].startswith('['):
            label = split_annot_utt[idx].lstrip('[')
            idx += 2
            BIO_SLOT = True
        elif split_annot_utt[idx].endswith(']'):
            if split_annot_utt[idx-1] == ":":
                labels.append("B-" + label)
                label = 'O'
                idx += 1
            else:
                labels.append("I-" + label)
                label = 'O'
                idx += 1
            BIO_SLOT = False
        else:
            if split_annot_utt[idx-1] == ":":
                labels.append("B-" + label)
                idx += 1
            elif BIO_SLOT:
                labels.append("I-" + label)
                idx += 1
            else:
                labels.append("O")
                idx += 1

    if len(tokens) != len(labels):
        raise ValueError(f"Length of tokens, {tokens}, doesn't match length of labels, {labels}, "
                         f"for id {id} and annot_utt: {annot_utt}")
    return tokens, labels, intent

sentences_tr, tags_tr, intent_tags_tr = [], [], []
sentences_val, tags_val, intent_tags_val = [], [], []
sentences_test, tags_test, intent_tags_test = [], [], []

massive_raw = []
with open('/content/drive/MyDrive/en-US.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        massive_raw.append(json.loads(line))

for id, sample in enumerate(massive_raw):
    tokens, labels, intent = create_tokens_and_labels(id, sample)
    if sample['partition'] == 'train':
        sentences_tr.append(tokens)
        tags_tr.append(labels)
        intent_tags_tr.append(intent)
    elif sample['partition'] == 'dev':
        sentences_val.append(tokens)
        tags_val.append(labels)
        intent_tags_val.append(intent)
    elif sample['partition'] == 'test':
        sentences_test.append(tokens)
        tags_test.append(labels)
        intent_tags_test.append(intent)


sentences_tr, _, tags_tr, _, intent_tags_tr, _ = train_test_split(
    sentences_tr, tags_tr, intent_tags_tr, test_size=0.9, random_state=42)

val_indices = random.sample(range(len(sentences_val)), 200)
sentences_val = [sentences_val[i] for i in val_indices]
tags_val = [tags_val[i] for i in val_indices]
intent_tags_val = [intent_tags_val[i] for i in val_indices]

test_indices = random.sample(range(len(sentences_test)), 200)
sentences_test = [sentences_test[i] for i in test_indices]
tags_test = [tags_test[i] for i in test_indices]
intent_tags_test = [intent_tags_test[i] for i in test_indices]

partition_counts = {'train': len(sentences_tr), 'test': len(sentences_test), 'dev': len(sentences_val)}
print("تعداد نمونه‌ها در هر بخش:", partition_counts)

تعداد نمونه‌ها در هر بخش: {'train': 1151, 'test': 200, 'dev': 200}

In [5]:
unique_slot_labels = set(label for sublist in tags_tr + tags_val + tags_test for label in sublist)
unique_intent_labels = set(intent_tags_tr + intent_tags_val + intent_tags_test)

label_list = sorted(unique_slot_labels.union(unique_intent_labels))

print("\nلیست برچسب‌های استخراج شده به صورت خودکار:")
print(label_list)

لیست برچسب‌های استخراج شده به صورت خودکار:
['B-alarm_type', 'B-app_name', 'B-artist_name', 'B-audiobook_author', 'B-audiobook_name', 'B-business_name', 'B-business_type', 'B-change_amount', 'B-color_type', 'B-cooking_type', 'B-currency_name', 'B-date', 'B-definition_word', 'B-device_type', 'B-email_address', 'B-email_folder', 'B-event_name', 'B-food_type', 'B-game_name', 'B-general_frequency', 'B-house_place', 'B-ingredient', 'B-joke_type', 'B-list_name', 'B-meal_type', 'B-media_type', 'B-movie_name', 'B-movie_type', 'B-music_descriptor', 'B-music_genre', 'B-news_topic', 'B-order_type', 'B-person', 'B-personal_info', 'B-place_name', 'B-player_setting', 'B-playlist_name', 'B-podcast_descriptor', 'B-podcast_name', 'B-radio_name', 'B-relation', 'B-song_name', 'B-time', 'B-time_zone', 'B-timeofday', 'B-transport_agency', 'B-transport_descriptor', 'B-transport_name', 'B-transport_type', 'B-weather_descriptor', 'I-alarm_type', 'I-artist_name', 'I-audiobook_author', 'I-audiobook_name', 'I-business_name', 'I-business_type', 'I-change_amount', 'I-color_type', 'I-currency_name', 'I-date', 'I-definition_word', 'I-device_type', 'I-email_address', 'I-event_name', 'I-food_type', 'I-game_name', 'I-general_frequency', 'I-house_place', 'I-ingredient', 'I-list_name', 'I-media_type', 'I-movie_name', 'I-movie_type', 'I-music_descriptor', 'I-music_genre', 'I-news_topic', 'I-order_type', 'I-person', 'I-personal_info', 'I-place_name', 'I-player_setting', 'I-playlist_name', 'I-podcast_descriptor', 'I-podcast_name', 'I-radio_name', 'I-relation', 'I-song_name', 'I-time', 'I-time_zone', 'I-timeofday', 'I-transport_descriptor', 'I-transport_name', 'I-weather_descriptor', 'O', 'alarm_query', 'alarm_remove', 'alarm_set', 'audio_volume_down', 'audio_volume_mute', 'audio_volume_other', 'audio_volume_up', 'calendar_query', 'calendar_remove', 'calendar_set', 'cooking_query', 'cooking_recipe', 'datetime_convert', 'datetime_query', 'email_addcontact', 'email_query', 'email_querycontact', 'email_sendemail', 'general_greet', 'general_joke', 'general_quirky', 'iot_cleaning', 'iot_coffee', 'iot_hue_lightchange', 'iot_hue_lightdim', 'iot_hue_lightoff', 'iot_hue_lighton', 'iot_hue_lightup', 'iot_wemo_off', 'iot_wemo_on', 'lists_createoradd', 'lists_query', 'lists_remove', 'music_dislikeness', 'music_likeness', 'music_query', 'music_settings', 'news_query', 'play_audiobook', 'play_game', 'play_music', 'play_podcasts', 'play_radio', 'qa_currency', 'qa_definition', 'qa_factoid', 'qa_maths', 'qa_stock', 'recommendation_events', 'recommendation_locations', 'recommendation_movies', 'social_post', 'social_query', 'takeaway_order', 'takeaway_query', 'transport_query', 'transport_taxi', 'transport_ticket', 'transport_traffic', 'weather_query']

# create prompt

In [6]:
def create_prompt(sentence, intent, slots):

    sentence_text = ' '.join(sentence)
    slots_text = ' '.join(slots)
    prompt = f'Input: {sentence_text}\nOutput Intent: {intent}\nOutput Slots: {slots_text}'
    return prompt

train_prompts = [create_prompt(sent, intent, slots) for sent, intent, slots in zip(sentences_tr, intent_tags_tr, tags_tr)]

val_prompts = [create_prompt(sent, intent, slots) for sent, intent, slots in zip(sentences_val, intent_tags_val, tags_val)]

test_prompts = [create_prompt(sent, intent, slots) for sent, intent, slots in zip(sentences_test, intent_tags_test, tags_test)]

print("نمونه‌های پرامپت‌های آموزشی:")
for i in range(2):
    print(f"Training Prompt {i+1}:")
    print(train_prompts[i])
    print("\n")


print("نمونه‌های پرامپت‌های اعتبارسنجی:")
for i in range(2):
    print(f"Validation Prompt {i+1}:")
    print(val_prompts[i])
    print("\n")


print("نمونه‌های پرامپت‌های تست:")
for i in range(2):
    print(f"Test Prompt {i+1}:")
    print(test_prompts[i])
    print("\n")

نمونه‌های پرامپت‌های آموزشی:
Training Prompt 1:
Input: please remove dinner date scheduled for this friday at nine p. m.
Output Intent: calendar_remove
Output Slots: O O B-meal_type O O O O B-date O B-time I-time I-time


Training Prompt 2:
Input: read freds emails
Output Intent: email_query
Output Slots: O B-person O


نمونه‌های پرامپت‌های اعتبارسنجی:
Validation Prompt 1:
Input: what is the weather supposed to be like this week
Output Intent: weather_query
Output Slots: O O O O O O O O B-date I-date


Validation Prompt 2:
Input: what will be the temperature today for miami florida
Output Intent: weather_query
Output Slots: O O O O B-weather_descriptor B-date O B-place_name I-place_name


نمونه‌های پرامپت‌های تست:
Test Prompt 1:
Input: what is the timing of bagmati express
Output Intent: transport_query
Output Slots: O O O O O B-transport_name I-transport_name


Test Prompt 2:
Input: my day is going well add a memo
Output Intent: general_quirky
Output Slots: O O O O O O O O

# پیش پردازش و توکنایز

In [7]:
def tokenize_function(examples):

    tokenized = tokenizer(
        examples['text'],
        padding='max_length',
        truncation=True,
        max_length=70,
        return_offsets_mapping=True
    )

    labels = []
    for i, slot_labels in enumerate(examples['slot_labels']):
        label_ids = [-100] * len(tokenized['input_ids'][i])

        output_slots_prefix = 'Output Slots: '
        output_slots_prefix_ids = tokenizer.encode(output_slots_prefix, add_special_tokens=False)

        try:

            prefix_start = tokenized['input_ids'][i].index(output_slots_prefix_ids[0])
            for j in range(len(output_slots_prefix_ids)):
                label_ids[prefix_start + j] = -100
            slot_start = prefix_start + len(output_slots_prefix_ids)

            for k, slot in enumerate(slot_labels):
                if slot in label_list:
                    label_id = label_list.index(slot)
                    if slot_start + k < len(label_ids):
                        label_ids[slot_start + k] = label_id
                else:
                    label_ids[slot_start + k] = -100
        except ValueError:

            pass

        labels.append(label_ids)

    tokenized['labels'] = labels
    return tokenized

train_data = {'text': train_prompts, 'slot_labels': tags_tr}
val_data = {'text': val_prompts, 'slot_labels': tags_val}
test_data = {'text': test_prompts, 'slot_labels': tags_test}


train_dataset = Dataset.from_dict(train_data)
val_dataset = Dataset.from_dict(val_data)
test_dataset = Dataset.from_dict(test_data)


dataset = DatasetDict({
    'train': train_dataset,
    'validation': val_dataset,
    'test': test_dataset
})

tokenized_datasets = dataset.map(tokenize_function, batched=True)

Map:   0%|          | 0/1151 [00:00<?, ? examples/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

In [8]:
def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    preds = np.argmax(predictions, axis=-1)

    preds = preds.tolist()
    labels = labels.tolist()

    true_labels = []
    true_preds = []

    for pred, label in zip(preds, labels):
        temp_true_labels = []
        temp_true_preds = []
        for p, l in zip(pred, label):
            if l != -100:
                temp_true_labels.append(l)
                temp_true_preds.append(p)
        true_labels.append(temp_true_labels)
        true_preds.append(temp_true_preds)

    true_labels_text = [[label_list[l] for l in labels] for labels in true_labels]
    preds_text = [[label_list[p] for p in preds] for preds in true_preds]

    slot_f1_micro = seq_f1(true_labels_text, preds_text, average='micro')
    slot_precision_micro = seq_precision(true_labels_text, preds_text, average='micro')
    slot_recall_micro = seq_recall(true_labels_text, preds_text, average='micro')


    true_intents = [labels[-1] for labels in true_labels if len(labels) > 0]
    pred_intents = [preds[-1] for preds in true_preds if len(preds) > 0]


    true_intents_text = [label_list[l] for l in true_intents]
    pred_intents_text = [label_list[p] for p in pred_intents]


    intent_f1_micro = sklearn_f1(true_intents_text, pred_intents_text, average='micro')
    intent_precision_micro = sklearn_precision(true_intents_text, pred_intents_text, average='micro')
    intent_recall_micro = sklearn_recall(true_intents_text, pred_intents_text, average='micro')

    return {
        'slot_f1_micro': slot_f1_micro,
        'slot_precision_micro': slot_precision_micro,
        'slot_recall_micro': slot_recall_micro,
        'intent_f1_micro': intent_f1_micro,
        'intent_precision_micro': intent_precision_micro,
        'intent_recall_micro': intent_recall_micro,
    }

# آموزش

In [9]:
training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=5,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=4,
    learning_rate=5e-5,
    logging_dir='./logs',
    logging_steps=50,
    save_total_limit=2,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    fp16=True,
    gradient_checkpointing=True,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    report_to=[],
)


trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['validation'],
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
)


trainer.train()
torch.cuda.empty_cache()

trainer.save_model('./trained_gpt2_model1')
torch.cuda.empty_cache()

/usr/local/lib/python3.10/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
<ipython-input-9-d6312d607bda>:22: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

# ارزیابی

In [10]:
def get_labels(predictions, label_ids):

    preds = np.argmax(predictions, axis=-1)
    labels = label_ids

    preds = preds.tolist()
    labels = labels.tolist()

    true_labels = []
    true_preds = []

    for pred, label in zip(preds, labels):
        temp_true_labels = []
        temp_true_preds = []
        for p, l in zip(pred, label):
            if l != -100:
                temp_true_labels.append(l)
                temp_true_preds.append(p)
        true_labels.append(temp_true_labels)
        true_preds.append(temp_true_preds)

    return true_labels, true_preds

def id_to_label(id_list, label_map):

    return [[label_map[id] for id in labels] for labels in id_list]

def predict_in_batches(trainer, dataset, batch_size=16):
    predictions = []
    label_ids = []
    for i in range(0, len(dataset), batch_size):
        batch = dataset.select(range(i, min(i + batch_size, len(dataset))))
        results = trainer.predict(batch)
        predictions.append(results.predictions)
        label_ids.append(results.label_ids)
        torch.cuda.empty_cache()
    predictions = np.concatenate(predictions, axis=0)
    label_ids = np.concatenate(label_ids, axis=0)
    return predictions, label_ids

val_predictions, val_label_ids = predict_in_batches(trainer, tokenized_datasets['validation'], batch_size=16)

val_true_labels, val_preds = get_labels(val_predictions, val_label_ids)

val_true_labels_text = id_to_label(val_true_labels, label_list)
val_preds_text = id_to_label(val_preds, label_list)

val_f1_micro = seq_f1(val_true_labels_text, val_preds_text, average='micro')
val_precision_micro = seq_precision(val_true_labels_text, val_preds_text, average='micro')
val_recall_micro = seq_recall(val_true_labels_text, val_preds_text, average='micro')

print("\nValidation Slot Filling Metrics (Micro):")
print(f"Precision: {val_precision_micro:.4f}")
print(f"Recall: {val_recall_micro:.4f}")
print(f"F1 Score: {val_f1_micro:.4f}")

val_f1_macro = seq_f1(val_true_labels_text, val_preds_text, average='macro')
val_precision_macro = seq_precision(val_true_labels_text, val_preds_text, average='macro')
val_recall_macro = seq_recall(val_true_labels_text, val_preds_text, average='macro')

print("\nValidation Slot Filling Metrics (Macro):")
print(f"Precision: {val_precision_macro:.4f}")
print(f"Recall: {val_recall_macro:.4f}")
print(f"F1 Score: {val_f1_macro:.4f}")

print("\nValidation Slot Filling Classification Report:")
print(classification_report(val_true_labels_text, val_preds_text, digits=4))

val_true_intents = [labels[-1] for labels in val_true_labels if len(labels) > 0]
val_pred_intents = [preds[-1] for preds in val_preds if len(preds) > 0]

val_true_intents_text = [label_list[id] for id in val_true_intents]
val_pred_intents_text = [label_list[id] for id in val_pred_intents]

intent_f1_micro = sklearn_f1(val_true_intents_text, val_pred_intents_text, average='micro')
intent_precision_micro = sklearn_precision(val_true_intents_text, val_pred_intents_text, average='micro')
intent_recall_micro = sklearn_recall(val_true_intents_text, val_pred_intents_text, average='micro')

print("\nValidation Intent Detection Metrics (Micro):")
print(f"Precision: {intent_precision_micro:.4f}")
print(f"Recall: {intent_recall_micro:.4f}")
print(f"F1 Score: {intent_f1_micro:.4f}")

intent_f1_macro = sklearn_f1(val_true_intents_text, val_pred_intents_text, average='macro')
intent_precision_macro = sklearn_precision(val_true_intents_text, val_pred_intents_text, average='macro')
intent_recall_macro = sklearn_recall(val_true_intents_text, val_pred_intents_text, average='macro')

print("\nValidation Intent Detection Metrics (Macro):")
print(f"Precision: {intent_precision_macro:.4f}")
print(f"Recall: {intent_recall_macro:.4f}")
print(f"F1 Score: {intent_f1_macro:.4f}")

print("\nValidation Intent Detection Classification Report (sklearn):")
print(sklearn_classification_report(val_true_intents_text, val_pred_intents_text, digits=4))

torch.cuda.empty_cache()

test_predictions, test_label_ids = predict_in_batches(trainer, tokenized_datasets['test'], batch_size=16)

test_true_labels, test_preds = get_labels(test_predictions, test_label_ids)

test_true_labels_text = id_to_label(test_true_labels, label_list)
test_preds_text = id_to_label(test_preds, label_list)

test_f1_micro = seq_f1(test_true_labels_text, test_preds_text, average='micro')
test_precision_micro = seq_precision(test_true_labels_text, test_preds_text, average='micro')
test_recall_micro = seq_recall(test_true_labels_text, test_preds_text, average='micro')

print("\nTest Slot Filling Metrics (Micro):")
print(f"Precision: {test_precision_micro:.4f}")
print(f"Recall: {test_recall_micro:.4f}")
print(f"F1 Score: {test_f1_micro:.4f}")

test_f1_macro = seq_f1(test_true_labels_text, test_preds_text, average='macro')
test_precision_macro = seq_precision(test_true_labels_text, test_preds_text, average='macro')
test_recall_macro = seq_recall(test_true_labels_text, test_preds_text, average='macro')

print("\nTest Slot Filling Metrics (Macro):")
print(f"Precision: {test_precision_macro:.4f}")
print(f"Recall: {test_recall_macro:.4f}")
print(f"F1 Score: {test_f1_macro:.4f}")


print("\nTest Slot Filling Classification Report:")
print(classification_report(test_true_labels_text, test_preds_text, digits=4))

test_true_intents = [labels[-1] for labels in test_true_labels if len(labels) > 0]
test_pred_intents = [preds[-1] for preds in test_preds if len(preds) > 0]

test_true_intents_text = [label_list[id] for id in test_true_intents]
test_pred_intents_text = [label_list[id] for id in test_pred_intents]


test_intent_f1_micro = sklearn_f1(test_true_intents_text, test_pred_intents_text, average='micro')
test_intent_precision_micro = sklearn_precision(test_true_intents_text, test_pred_intents_text, average='micro')
test_intent_recall_micro = sklearn_recall(test_true_intents_text, test_pred_intents_text, average='micro')

print("\nTest Intent Detection Metrics (Micro):")
print(f"Precision: {test_intent_precision_micro:.4f}")
print(f"Recall: {test_intent_recall_micro:.4f}")
print(f"F1 Score: {test_intent_f1_micro:.4f}")

test_intent_f1_macro = sklearn_f1(test_true_intents_text, test_pred_intents_text, average='macro')
test_intent_precision_macro = sklearn_precision(test_true_intents_text, test_pred_intents_text, average='macro')
test_intent_recall_macro = sklearn_recall(test_true_intents_text, test_pred_intents_text, average='macro')

print("\nTest Intent Detection Metrics (Macro):")
print(f"Precision: {test_intent_precision_macro:.4f}")
print(f"Recall: {test_intent_recall_macro:.4f}")
print(f"F1 Score: {test_intent_f1_macro:.4f}")

print("\nTest Intent Detection Classification Report (sklearn):")
print(sklearn_classification_report(test_true_intents_text, test_pred_intents_text, digits=4))

decoded_text = tokenizer.decode(tokenized_datasets['train'][0]['input_ids'], skip_special_tokens=True)
print("\nمتن بازگردانی‌شده:")
print(decoded_text)
original_text = tokenized_datasets['train'][0]['text']
print("\nمتن اصلی:")
print(original_text)

Validation Slot Filling Metrics (Micro):
Precision: 0.1908
Recall: 0.1784
F1 Score: 0.1844

Validation Slot Filling Metrics (Macro):
Precision: 0.0913
Recall: 0.0885
F1 Score: 0.0779

Validation Slot Filling Classification Report:
                    precision    recall  f1-score   support

        alarm_type     0.0000    0.0000    0.0000         1
       artist_name     0.0000    0.0000    0.0000         2
     business_name     0.0000    0.0000    0.0000         6
     business_type     1.0000    0.2000    0.3333         5
     change_amount     0.0000    0.0000    0.0000         2
        color_type     0.0000    0.0000    0.0000         1
     currency_name     0.0000    0.0000    0.0000         1
              date     0.2292    0.3929    0.2895        28
   definition_word     0.3333    0.5000    0.4000         4
       device_type     0.0000    0.0000    0.0000         2
     email_address     0.0000    0.0000    0.0000         1
      email_folder     0.0000    0.0000    0.0000         1
        event_name     0.2000    0.0667    0.1000        15
         food_type     0.3000    0.5000    0.3750         6
 general_frequency     0.0000    0.0000    0.0000         1
       house_place     0.0000    0.0000    0.0000         0
        ingredient     0.0000    0.0000    0.0000         1
         joke_type     0.0000    0.0000    0.0000         1
         list_name     0.0000    0.0000    0.0000         2
        media_type     0.0000    0.0000    0.0000        11
  music_descriptor     0.0000    0.0000    0.0000         1
       music_genre     0.0000    0.0000    0.0000         5
        news_topic     0.3333    0.2500    0.2857         4
        order_type     0.0000    0.0000    0.0000         2
            person     0.1818    0.1429    0.1600        14
     personal_info     0.1667    0.5000    0.2500         2
        place_name     0.1600    0.2222    0.1860        18
    player_setting     0.0000    0.0000    0.0000         3
     playlist_name     0.0000    0.0000    0.0000         2
podcast_descriptor     0.0000    0.0000    0.0000         1
      podcast_name     0.0000    0.0000    0.0000         1
        radio_name     0.2500    0.2000    0.2222         5
          relation     0.0000    0.0000    0.0000         3
         song_name     0.0000    0.0000    0.0000         4
              time     0.2632    0.2778    0.2703        18
         timeofday     0.0000    0.0000    0.0000         3
  transport_agency     0.0000    0.0000    0.0000         1
    transport_type     0.0000    0.0000    0.0000         2
weather_descriptor     0.1429    0.2000    0.1667         5

         micro avg     0.1908    0.1784    0.1844       185
         macro avg     0.0913    0.0885    0.0779       185
      weighted avg     0.1694    0.1784    0.1576       185


Validation Intent Detection Metrics (Micro):
Precision: 0.6050
Recall: 0.6050
F1 Score: 0.6050

Validation Intent Detection Metrics (Macro):
Precision: 0.2184
Recall: 0.1662
F1 Score: 0.1758

Validation Intent Detection Classification Report (sklearn):
                      precision    recall  f1-score   support

       B-artist_name     0.0000    0.0000    0.0000         0
     B-business_name     0.0000    0.0000    0.0000         2
     B-business_type     1.0000    0.5000    0.6667         2
        B-color_type     0.0000    0.0000    0.0000         1
              B-date     0.5333    0.6667    0.5926        12
   B-definition_word     1.0000    0.5000    0.6667         4
        B-event_name     0.0000    0.0000    0.0000         2
         B-food_type     0.5000    1.0000    0.6667         2
       B-house_place     0.0000    0.0000    0.0000         0
        B-media_type     0.0000    0.0000    0.0000         3
       B-music_genre     0.0000    0.0000    0.0000         2
        B-news_topic     0.0000    0.0000    0.0000         2
        B-order_type     0.0000    0.0000    0.0000         0
            B-person     0.3333    0.3333    0.3333         3
     B-personal_info     0.0000    0.0000    0.0000         0
        B-place_name     0.3000    0.4286    0.3529         7
          B-relation     0.0000    0.0000    0.0000         1
         B-song_name     0.0000    0.0000    0.0000         1
              B-time     1.0000    0.5000    0.6667         2
         B-timeofday     0.0000    0.0000    0.0000         1
  B-transport_agency     0.0000    0.0000    0.0000         1
    B-transport_type     0.0000    0.0000    0.0000         0
B-weather_descriptor     0.0000    0.0000    0.0000         1
       I-artist_name     0.0000    0.0000    0.0000         1
     I-business_name     0.0000    0.0000    0.0000         1
     I-business_type     0.0000    0.0000    0.0000         1
     I-change_amount     0.0000    0.0000    0.0000         1
              I-date     0.6667    0.2222    0.3333         9
   I-definition_word     0.0000    0.0000    0.0000         0
       I-device_type     1.0000    0.5000    0.6667         2
         I-food_type     0.0000    0.0000    0.0000         2
        I-ingredient     0.0000    0.0000    0.0000         1
         I-list_name     0.0000    0.0000    0.0000         1
        I-media_type     0.0000    0.0000    0.0000         1
        I-news_topic     0.0000    0.0000    0.0000         0
            I-person     0.0000    0.0000    0.0000         1
     I-personal_info     0.0000    0.0000    0.0000         1
        I-place_name     0.0000    0.0000    0.0000         6
     I-playlist_name     0.0000    0.0000    0.0000         2
I-podcast_descriptor     0.0000    0.0000    0.0000         1
        I-radio_name     1.0000    0.7500    0.8571         4
         I-song_name     1.0000    0.3333    0.5000         3
              I-time     0.8000    0.8889    0.8421         9
         I-timeofday     0.0000    0.0000    0.0000         1
                   O     0.6929    0.8544    0.7652       103

            accuracy                         0.6050       200
           macro avg     0.2184    0.1662    0.1758       200
        weighted avg     0.5604    0.6050    0.5645       200

/usr/local/lib/python3.10/dist-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Test Slot Filling Metrics (Micro):
Precision: 0.1884
Recall: 0.1405
F1 Score: 0.1610

Test Slot Filling Metrics (Macro):
Precision: 0.0739
Recall: 0.0891
F1 Score: 0.0676

Test Slot Filling Classification Report:
                      precision    recall  f1-score   support

         artist_name     0.0000    0.0000    0.0000         1
      audiobook_name     0.0000    0.0000    0.0000         1
       business_name     0.0000    0.0000    0.0000         5
       business_type     0.0000    0.0000    0.0000         3
          color_type     0.0000    0.0000    0.0000         4
        cooking_type     0.0000    0.0000    0.0000         2
       currency_name     0.0000    0.0000    0.0000         3
                date     0.2632    0.2500    0.2564        20
     definition_word     0.1667    0.3333    0.2222         3
         device_type     0.2500    0.2500    0.2500         4
          event_name     0.0000    0.0000    0.0000        17
           food_type     0.2500    0.1667    0.2000         6
           game_name     0.0000    0.0000    0.0000         3
   general_frequency     0.0000    0.0000    0.0000         2
         house_place     0.0000    0.0000    0.0000         5
           joke_type     0.0000    0.0000    0.0000         2
           list_name     0.0000    0.0000    0.0000         3
           meal_type     0.0000    0.0000    0.0000         2
          media_type     0.0000    0.0000    0.0000         8
    music_descriptor     0.0000    0.0000    0.0000         1
         music_genre     0.0000    0.0000    0.0000         6
          order_type     0.2000    1.0000    0.3333         1
              person     0.6667    0.1538    0.2500        13
          place_name     0.2353    0.4000    0.2963        20
      player_setting     0.0000    0.0000    0.0000         3
       playlist_name     0.0000    0.0000    0.0000         1
  podcast_descriptor     0.0000    0.0000    0.0000         2
        podcast_name     0.0000    0.0000    0.0000         1
          radio_name     0.0000    0.0000    0.0000         3
            relation     0.0000    0.0000    0.0000         5
                time     0.1667    0.2667    0.2051        15
           time_zone     0.0000    0.0000    0.0000         1
           timeofday     0.0000    0.0000    0.0000         4
transport_descriptor     0.0000    0.0000    0.0000         1
      transport_name     0.0000    0.0000    0.0000         1
      transport_type     0.2857    0.3333    0.3077         6
  weather_descriptor     0.2500    0.1429    0.1818         7

           micro avg     0.1884    0.1405    0.1610       185
           macro avg     0.0739    0.0891    0.0676       185
        weighted avg     0.1503    0.1405    0.1281       185


Test Intent Detection Metrics (Micro):
Precision: 0.6850
Recall: 0.6850
F1 Score: 0.6850

Test Intent Detection Metrics (Macro):
Precision: 0.2043
Recall: 0.1884
F1 Score: 0.1915

Test Intent Detection Classification Report (sklearn):
                      precision    recall  f1-score   support

        B-color_type     0.0000    0.0000    0.0000         4
      B-cooking_type     0.0000    0.0000    0.0000         1
     B-currency_name     0.0000    0.0000    0.0000         1
              B-date     0.6667    0.5714    0.6154         7
   B-definition_word     0.5000    0.5000    0.5000         2
       B-device_type     0.0000    0.0000    0.0000         1
        B-event_name     0.0000    0.0000    0.0000         2
         B-food_type     0.3333    0.5000    0.4000         2
         B-game_name     0.0000    0.0000    0.0000         1
       B-house_place     0.0000    0.0000    0.0000         0
        B-media_type     0.0000    0.0000    0.0000         1
       B-music_genre     0.0000    0.0000    0.0000         1
        B-order_type     1.0000    1.0000    1.0000         1
            B-person     1.0000    0.4000    0.5714         5
        B-place_name     0.6364    0.7778    0.7000         9
          B-relation     0.0000    0.0000    0.0000         2
              B-time     0.0000    0.0000    0.0000         0
         B-timeofday     0.0000    0.0000    0.0000         2
    B-transport_type     0.0000    0.0000    0.0000         0
B-weather_descriptor     0.0000    0.0000    0.0000         1
       I-artist_name     0.0000    0.0000    0.0000         1
     I-business_name     0.0000    0.0000    0.0000         1
     I-business_type     0.0000    0.0000    0.0000         1
              I-date     0.5000    0.3333    0.4000         3
   I-definition_word     0.0000    0.0000    0.0000         1
       I-device_type     0.5000    0.5000    0.5000         2
        I-event_name     0.0000    0.0000    0.0000         2
         I-game_name     0.0000    0.0000    0.0000         1
 I-general_frequency     0.0000    0.0000    0.0000         1
       I-house_place     0.0000    0.0000    0.0000         1
        I-media_type     1.0000    1.0000    1.0000         1
  I-music_descriptor     0.0000    0.0000    0.0000         0
       I-music_genre     0.0000    0.0000    0.0000         1
            I-person     0.0000    0.0000    0.0000         1
        I-place_name     0.0000    0.0000    0.0000         3
I-podcast_descriptor     0.0000    0.0000    0.0000         2
        I-radio_name     0.5000    0.3333    0.4000         3
              I-time     1.0000    0.9091    0.9524        11
    I-transport_name     0.0000    0.0000    0.0000         1
I-weather_descriptor     0.0000    0.0000    0.0000         1
                   O     0.7379    0.8992    0.8106       119

            accuracy                         0.6850       200
           macro avg     0.2043    0.1884    0.1915       200
        weighted avg     0.6094    0.6850    0.6380       200


متن بازگردانی‌شده:
Input: please remove dinner date scheduled for this friday at nine p. m.
Output Intent: calendar_remove
Output Slots: O O B-meal_type O O O O B-date O B-time I-time I-time

متن اصلی:
Input: please remove dinner date scheduled for this friday at nine p. m.
Output Intent: calendar_remove
Output Slots: O O B-meal_type O O O O B-date O B-time I-time I-time

/usr/local/lib/python3.10/dist-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))